### ISSUE TITLE
No light control after upgrading to 1.0

### ISSUE THREAD

**Issue by gtenney99** [entrippy/OctoPrint-OctoHue#62]
**Describe the bug**
I have upgraded to 1.0 on both of my octoprint systems.
Post upgrade, I am unable to select lights, as there is nothing to select from

<img width="756" height="273" alt="Image" src="https://github.com/user-attachments/assets/b6b3f5f0-810e-4f47-8f48-83148c3f714e" />

On my second system I removed/reinstalled 1.0 and was unable to pair.

Both systems are on Octoprint 1.11.7
and Python 3.9.2

**To Reproduce**
1. Upgrade to octohue 1.0

Logs from upgraded Pi
`2026-04-04 23:01:45,356 - octoprint.plugins.klipper - INFO - get_cfg_files Path: /home/pi/printer_data/config/printer.cfg
2026-04-04 23:01:45,981 - octoprint.plugins.excluderegion - WARNING - The simple API of this plugin is relying on the default implementation of is_api_protected (newly added in OctoPrint 1.11.2), which in a future version will be switched from False to True for security reasons. Plugin authors should ensure they explicitly declare the API protection status in their SimpleApiPlugin mixin implementation. 
2026-04-04 23:01:51,937 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:51,938 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:51,954 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:51,954 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:53,609 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:53,610 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:53,623 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:53,624 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,005 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,006 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,018 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,019 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,281 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,282 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,296 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,296 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,448 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,448 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,454 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,455 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,637 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,637 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,644 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,644 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,815 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,815 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,822 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,822 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,992 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:55,992 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:55,997 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:55,998 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:56,212 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light/
2026-04-04 23:01:56,213 - octoprint.plugins.octohue - ERROR - Hue API error (GET light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:01:56,225 - octoprint.plugins.octohue - INFO - Hue API PUT https://192.168.10.52/clip/v2/resource/light/ payload={'on': {'on': True}}
2026-04-04 23:01:56,228 - octoprint.plugins.octohue - ERROR - Hue API error (PUT light/): 'NoneType' object has no attribute 'request'
2026-04-04 23:02:06,089 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light
2026-04-04 23:02:06,089 - octoprint.plugins.octohue - ERROR - Hue API error (GET light): 'NoneType' object has no attribute 'request'
2026-04-04 23:02:06,118 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light
2026-04-04 23:02:06,119 - octoprint.plugins.octohue - ERROR - Hue API error (GET light): 'NoneType' object has no attribute 'request'
2026-04-04 23:02:06,595 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/room
2026-04-04 23:02:06,596 - octoprint.plugins.octohue - ERROR - Hue API error (GET room): 'NoneType' object has no attribute 'request'
2026-04-04 23:02:06,596 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/zone
2026-04-04 23:02:06,596 - octoprint.plugins.octohue - ERROR - Hue API error (GET zone): 'NoneType' object has no attribute 'request'
2026-04-04 23:03:11,545 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:07:11,633 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:11:11,724 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:14:02,421 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2026-04-04 23:15:11,807 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:19:11,884 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:23:11,961 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:27:12,042 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:29:02,422 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2026-04-04 23:31:12,135 - octoprint.server.util - WARNING - The global API key was just used. The global API key is deprecated and will cease to function with OctoPrint 1.13.0.
2026-04-04 23:34:48,560 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light
2026-04-04 23:34:48,561 - octoprint.plugins.octohue - ERROR - Hue API error (GET light): 'NoneType' object has no attribute 'request'
2026-04-04 23:34:48,567 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/light
2026-04-04 23:34:48,575 - octoprint.plugins.octohue - ERROR - Hue API error (GET light): 'NoneType' object has no attribute 'request'
2026-04-04 23:34:50,021 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/room
2026-04-04 23:34:50,022 - octoprint.plugins.octohue - ERROR - Hue API error (GET room): 'NoneType' object has no attribute 'request'
2026-04-04 23:34:50,022 - octoprint.plugins.octohue - INFO - Hue API GET https://192.168.10.52/clip/v2/resource/zone
2026-04-04 23:34:50,023 - octoprint.plugins.octohue - ERROR - Hue API error (GET zone): 'NoneType' object has no attribute 'request'
2026-04-04 23:34:58,555 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.65`

Logs after attempting clean install of octohue
`FileNotFoundError: [Errno 2] No such file or directory
2026-04-04 23:20:15,009 - tornado.access - ERROR - 500 POST /api/plugin/octohue (192.168.10.207) 41.85ms
2026-04-04 23:20:15,989 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 173, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1692, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 483, in on_api_command
    pair_session.mount("https://", _SignifyAdapter())
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/adapters.py", line 222, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 27, in init_poolmanager
    ctx = ssl.create_default_context(cafile=_CA_BUNDLE)
  File "/usr/lib/python3.9/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
2026-04-04 23:20:16,008 - tornado.access - ERROR - 500 POST /api/plugin/octohue (192.168.10.207) 40.74ms
2026-04-04 23:20:16,988 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 173, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1692, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 483, in on_api_command
    pair_session.mount("https://", _SignifyAdapter())
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/adapters.py", line 222, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 27, in init_poolmanager
    ctx = ssl.create_default_context(cafile=_CA_BUNDLE)
  File "/usr/lib/python3.9/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
2026-04-04 23:20:17,007 - tornado.access - ERROR - 500 POST /api/plugin/octohue (192.168.10.207) 41.42ms
2026-04-04 23:20:17,984 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 173, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1692, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 483, in on_api_command
    pair_session.mount("https://", _SignifyAdapter())
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/adapters.py", line 222, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 27, in init_poolmanager
    ctx = ssl.create_default_context(cafile=_CA_BUNDLE)
  File "/usr/lib/python3.9/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
2026-04-04 23:20:18,002 - tornado.access - ERROR - 500 POST /api/plugin/octohue (192.168.10.207) 39.70ms
2026-04-04 23:20:18,983 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin octohue
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 173, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1692, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 483, in on_api_command
    pair_session.mount("https://", _SignifyAdapter())
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/adapters.py", line 222, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octohue/__init__.py", line 27, in init_poolmanager
    ctx = ssl.create_default_context(cafile=_CA_BUNDLE)
  File "/usr/lib/python3.9/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
2026-04-04 23:20:19,001 - tornado.access - ERROR - 500 POST /api/plugin/octohue (192.168.10.207) 39.09ms`

**Expected behavior**
Expect light control to still work or to be able to re-pair.

**Desktop (please complete the following information):**
 - OS: MacOS X, Windows 11, iOS
 - Browser Firefox/Chrome/Safari
 

**Additional context**
I rolled back to 0.9.0 as a workaround for the time being.

**Comment by entrippy** [comment]
pretty sure this is fixed. Did a fresh install and it worked for me.

**Comment by gtenney99** [comment]
It is indeed fixed, Thanks for the quick fix!
